version: 2

jobs:
  test-frontend:
    docker:
      - image: circleci/node:6.11.4
    steps:
      - checkout
      - run:
          name: install yarn
          command: 'npm install -g yarn --quiet'
      - run:
          name: yarn install
          command: 'yarn install --pure-lockfile --no-progress'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: jest tests
          command: npm run jest

workflows:
  version: 2
  test:
    jobs:
      - test-frontend
